config/routes.rb
Kit::Application.routes.draw do

  root to: 'webpages#landing'

  resources :users, only: [:new, :create, :index, :update, :show, :destroy]
  match '/signup',  to: 'users#new'

  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  resources :invitations, only: [:index, :create]
  match '/invitations_new_signup', to: 'invitations#new_signup'
  match '/invitations_accept_signup', to: 'invitations#accept_signup', via: :post
  match '/invitations_new_signin', to: 'invitations#new_signin'
  match '/invitations_accept_signin', to: 'invitations#accept_signin', via: :post

  resources :contacts, only: [:index]
  
  resources :passwords, only: [:new, :create, :edit, :update]
  match '/reset_new',  to: 'passwords#reset_new'
  match '/reset_update',  to: 'passwords#reset_update', via: :put

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation, 
                  :remember_token, :account_token, :name, :phone, :description
  has_secure_password

  has_many :invitations, dependent: :destroy
  has_many :relationships, foreign_key: "inviter_id", dependent: :destroy
  has_many :invitees, through: :relationships, source: :invitee
  has_many :reverse_relationships, foreign_key: "invitee_id", class_name: "Relationship", dependent: :destroy
  has_many :inviters, through: :reverse_relationships, source: :inviter

  before_save { |user| user.email = email.downcase }
  before_save :create_tokens

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true
  validates :name, presence: true, length: { minimum: 2 }

  private

  	def create_tokens
  	  self.remember_token = SecureRandom.urlsafe_base64
      self.account_token = SecureRandom.urlsafe_base64
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # filter of show should be contacts user, to be developed
  before_filter :signed_in_user, only: [:index, :update, :show, :destroy]
  before_filter :myself_or_admin_user, only: [:update]
  before_filter :users_show_authorized_user, only: [:show]
  before_filter :admin_user, only: [:index, :destroy]

  def index
    @users = User.all
    @invitation = Invitation.new
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(params[:user])
  	if @user.save
      sign_in(@user, params[:page][:remember_me])
      flash[:success] = "Welcome to JingsApp!"
      redirect_to contacts_path
  	else
  	  flash.now[:error] = @user.errors.full_messages[0]
      render 'new'
  	end
  end

  def edit
    @user = User.find(params[:id])
    @invitation = Invitation.new
  end

  def update
    @user = User.find(params[:id])
    if update_without_password(@user, params[:user])
      flash[:success] = "Profile updated"
      sign_in(@user,"yes")
      redirect_to user_path(current_user)
    else
      flash.now[:error] = @user.errors.full_messages[0]
      redirect_to user_path(current_user)
    end
  end

  def show
    @user = User.find(params[:id])
    @invitation = Invitation.new
  end

  def destroy
    user = User.find(params[:id])
    flash[:success] = "User #{user.email} destroyed."
    user.destroy
    redirect_to users_path
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_all_users_table.html.erb
<div class="div-table">
<table class="table">
  <thead>
    <tr>
    	<th>Email</th>
      <th>Name</th>
      <th>Contacts</th>
    	<th>Registeration</th>
      <th>Last Update</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>   
        <td class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown", tabindex= "-1">
            <%= user.email %>
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Profile", user_path(user) %></li>
            <li class="divider"></li>
            <li>
              <%= link_to "Delete", user, method: :delete, data: { confirm: " Are you sure?" } %>
            </li>
          </ul>
        </td>
        <td><%= user.name %></td>
        <td><%= get_contacts_by_user(user).count %></td>
        <td><%= user.created_at.to_formatted_s(:db) %></td>
        <td><%= user.updated_at.to_formatted_s(:db) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<div>
  <p><h5>&nbsp;&nbsp;&nbsp;Total User: <%= @users.count %></h5></p>
</div>  

app/views/users/_profile_table.html.erb
<table class="table table-bordered">
  <tr>
  	<td><strong>Name:</strong></td>
    <td><%= @user.name %></td>
  </tr>
  <tr>
    <td><strong>Email:</strong></td>
    <td><%= @user.email %></td>
  </tr>
  <tr>
    <td><strong>Phone Number:</strong></td>
    <td><%= @user.phone %></td>
  </tr>
  <tr>
    <td><strong>Description:</strong></td>
    <td><%= @user.description %></td>
  </tr>
  <tr>
    <td><strong>Registeration:</strong></td>
    <td><%= @user.created_at %></td>
  </tr>
  <tr>
    <td><strong>Last Update:</strong></td>
    <td><%= @user.updated_at %></td>
  </tr>
</table>
<% if myself? %>
<a href="#update_profile_modal" role="button" class="btn btn-primary" data-toggle="modal">Edit</a>
<div id="update_profile_modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="update_profile_label" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="update_profile_label">Update your profile</h3>
  </div>
  <div class="modal-body">
    
    <%= form_for @user, html: {class: "form-horizontal"} do |f| %>
      <div class="control-group">
        <%= f.label :name, class: "control-label" %>
        <div class="controls">
          <%= f.text_field :name, placeholder: "Full Name" %>
        </div>
      </div>      
      <div class="control-group">
        <%= f.label :phone, class: "control-label" %>
        <div class="controls">
          <%= f.text_field :phone, placeholder: "Phone Number" %>
        </div>
      </div>
      <div class="control-group">
        <%= f.label :description, class: "control-label" %>
        <div class="controls">
          <%= f.text_area :description, rows:3, placeholder: "Your Self-description: e.g. US President" %>
        </div>
      </div>
  </div>
  <div class="modal-footer">
      <%= f.submit "Save", class: "btn btn-primary pull-left" %>
    <% end %>
    <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
  </div>
</div>
<% end %>

app/views/users/_signup_form.html.erb
<%= form_for @user, url: '/users' do |f| %>
  <label><h4>New to JingsApp?</h4></label>
  <%= f.text_field :email, placeholder: "Email" %>
  <%= f.text_field :name, placeholder: "Full Name" %>
  <%= f.password_field :password, placeholder: "Password" %>
  <%= f.password_field :password_confirmation, placeholder: "Re-type password" %>
  <label class="checkbox">
  	<%= check_box("page", "remember_me", { checked: true }, "yes", "no") %>
  	<small>Remember me</small>  	
  </label>
  <%= f.submit "Create my account", class: "btn btn-warning" %>
  <br>
<% end %>

app/views/users/index.html.erb
<% provide(:title, 'All Users') %>
<% provide(:sub_title, 'All Users') %>
<div class = "row">
  <div class = "span12">
    <%= render 'users/all_users_table' %>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<div class= "span4 offset4">
  <%= render 'users/signup_form' %>
  <br>
  <p>Alreday have an account? <%= link_to "Sign in", signin_path %></p>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<% provide(:sub_title, 'Profile') %>
<div class="row">
  <div class="span12">
  	<p><h4> 
  	  <% if myself? %>Your Profile<% else %>Information  | <%= @user.name %><% end %>
	</h4></p>
	<%= render 'users/profile_table' %>
  </div>
</div>