config/routes.rb
Kit::Application.routes.draw do

  root to: 'webpages#landing'

  resources :users, only: [:new, :create, :index, :update, :show, :destroy]
  match '/signup',  to: 'users#new'

  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  resources :invitations, only: [:index, :create]
  match '/invitations_new_signup', to: 'invitations#new_signup'
  match '/invitations_accept_signup', to: 'invitations#accept_signup', via: :post
  match '/invitations_new_signin', to: 'invitations#new_signin'
  match '/invitations_accept_signin', to: 'invitations#accept_signin', via: :post

  resources :contacts, only: [:index]
  
  resources :passwords, only: [:new, :create, :edit, :update]
  match '/reset_new',  to: 'passwords#reset_new'
  match '/reset_update',  to: 'passwords#reset_update', via: :put

end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  attr_accessible :email, :status, :token, :user_id, 
                  :name, :phone, :description, :message
  belongs_to :user
  has_one :relationship

  before_save { |user| user.email = email.downcase }
  before_save :create_token

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
  validates :user_id, presence: true

  private

  def create_token
    self.token = SecureRandom.urlsafe_base64
  end

end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  
  # Invitations' filter to be set

  def new_signup
    @user = User.new
    unless @invitation = Invitation.find_by_token(params[:token])
      flash[:error] = "Ooops...The link has expired"
      redirect_to root_path
    end
  end

  def accept_signup
    @user = User.new(params[:user])
    @invitation = Invitation.find_by_token(params[:page][:token])
    if @user.save
      create_relationship(@invitation, @user)
      sign_in(@user, params[:page][:remember_me])
      flash[:success] = "Your infomation has been sent back to #{@invitation.user.name}"
      redirect_to contacts_path
    else
      flash[:error] = @user.errors.full_messages[0]
      redirect_to invitations_new_signup_path + "?token=#{params[:page][:token]}"
    end
  end

  def new_signin
    unless @invitation = Invitation.find_by_token(params[:token])
      flash[:error] = "Ooops...The link has expired"
      redirect_to root_path
    end
  end

  def accept_signin
    user = User.find_by_email(params[:session][:email].downcase)
    invitation = Invitation.find_by_token(params[:page][:token])
    if user && user.authenticate(params[:session][:password])
      create_relationship(invitation, user)
      sign_in(user, params[:remember_me])
      flash[:success] = "You are now connected with " + invitation.user.name
      redirect_to contacts_path
    else
      flash[:error] = 'Invalid email or password'
      redirect_to invitations_new_signin_path + "?token=#{params[:page][:token]}"
    end
  end

  def index
    @invitation = Invitation.new    
    @received_invitations = Invitation.where("email = ? AND status = ?", current_user.email, "new")
    @sent_invitations = current_user.invitations.where("status = ?", "new")
  end

  def create
  	@invitation = Invitation.new(params[:invitation])
    @invitation.email = @invitation.email.downcase
  	if add_self?(@invitation.email)
      flash[:error] = "You can't add yourself"
      redirect_to contacts_path
    elsif current_contact_by_email?(@invitation.email)
      flash[:notice] = "You already have the information of " + User.find_by_email(@invitation.email).name + " (#{@invitation.email})"
      redirect_to contacts_path
    elsif already_invited_by?(@invitation.email)
      accept_original_invitation(@invitation)
      flash[:notice] = "You are now connected with" + User.find_by_email(@invitation.email).name + " (#{@invitation.email})"
      redirect_to contacts_path
    elsif existing_invitation_to?(@invitation.email)
      flash[:success] = "An reminding email sent to #{@invitation.email}"
      redirect_to invitations_path
      send_invitation(@invitation)
    elsif @invitation.save
      flash[:success] = "An invitation sent to #{@invitation.email}"
      redirect_to invitations_path
      send_invitation(@invitation)
  	else
  	  flash[:error] = @invitation.errors.full_messages[0]
      redirect_to invitations_path
  	end
  end

end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/views/invitations/_accept_invitation_form.html.erb
<%= form_for @user, url: '/invitations_accept_signup' do |f| %>
  <label><h4>Send your information back<%=  %></h4></label>
  <%= hidden_field :page, :token, value: params[:token] %>
  <%= f.text_field :name, placeholder: "Full Name" %>
  <%= f.text_field :email, placeholder: "Email", value: @invitation.email %>
  <%= f.text_field :phone, placeholder: "Phone number" %>
  <br><br>
  <label><h4>Set a password to protect your information</h4></label>
  <%= f.password_field :password, placeholder: "Password" %>
  <%= f.password_field :password_confirmation, placeholder: "Re-type password" %>
  <label class="checkbox"><%= check_box("page", "remember_me", { checked: true }, "yes", "no") %> Remember me</label>
  <%= f.submit "Send to #{Invitation.find_by_token(params[:token]).user.name}", class: "btn btn-warning signup-btn" %>
  <br>
<% end %>

app/views/invitations/_accept_invitation_signin_form.html.erb
<%= form_for :session, url: invitations_accept_signin_path do |f| %>
  <label><h4>Sign in to send your information back</h4></label>
  <%= hidden_field :page, :token, value: params[:token] %>
  <%= f.text_field :email, placeholder: "Email" %>
  <%= f.password_field :password, placeholder: "Password" %>
  <label class="checkbox"><%= f.check_box :remember_me, { checked: true }, "yes", "no" %> Remember me</label>
  <%= f.submit "Sign in to connect to #{Invitation.find_by_token(params[:token]).user.name}", class: "btn btn-primary signin-btn" %>
  <br>
<% end %>

app/views/invitations/_accept_invitation_signup_form.html.erb
<%= form_for @user, url: '/invitations_accept_signup' do |f| %>
  <label><h4>Send your information back</h4></label>
  <%= hidden_field :page, :token, value: params[:token] %>
  <%= f.text_field :name, placeholder: "Full Name" %>
  <%= f.text_field :email, placeholder: "Email", value: @invitation.email %>
  <%= f.text_field :phone, placeholder: "Phone number" %>
  <br><br>
  <label><h4>Set a password to protect your information</h4></label>
  <%= f.password_field :password, placeholder: "Password" %>
  <%= f.password_field :password_confirmation, placeholder: "Re-type password" %>
  <label class="checkbox"><%= check_box("page", "remember_me", { checked: true }, "yes", "no") %> Remember me</label>
  <%= f.submit "Send to #{Invitation.find_by_token(params[:token]).user.name}", class: "btn btn-warning signup-btn" %>
  <br>
<% end %>

app/views/invitations/_invitations_table.html.erb
<table class="table table-bordered">
  <tr>
  	<th>Email</th>
  	<th>Time</th>
  </tr>
  <% @invitations.each do |invitation| %>
    <tr>
      <td><%= invitation.email %></td>
      <td><%= invitation.created_at.to_formatted_s(:db) %></td>
    </tr>
  <% end %>
</table>

app/views/invitations/_invite_form.html.erb
<%= form_for @invitation, html: {class: "form-inline"} do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id  %>
  <%= f.text_field :email, placeholder: "Input email" %>
  <%= f.submit "  Add +  ", class: "btn btn-small btn-primary" %>
<% end %>

app/views/invitations/_received_invitations_table.html.erb
<% if @received_invitations.any? %>
<div class="div-table">
<table class="table">
  <thead>
    <tr>
      <th>Received</th>
      <th>Name</th>
      <th>Email</th>
      <th>Description</th>
      <th>Received at</th>
    </tr>
  </thead>
  <tbody>
    <% @received_invitations.each do |invitation| %>
      <tr>
        <td>
          <div class="btn-group">
            <button type="button" class="btn btn-mini btn-success btn-accept" data-loading-text="Accepted">Accept</button>
            <button class="btn btn-mini dropdown-toggle" data-toggle="dropdown">
              <span class="caret"></span>
            </button>
            <ul class="dropdown-menu">
              <li><%= link_to "Reject", '#' %></li>
            </ul>
          </div>          
        </td>
        <td><%= invitation.user.name %></td>
        <td><%= invitation.user.email %></td>
        <td><%= invitation.user.description %></td>
        <td><%= invitation.created_at.to_formatted_s(:db) %></td>
      </tr>
    <% end %>
  </tbody>       
</table>
</div>

<div>
  <p><h5>&nbsp;&nbsp;&nbsp;Total Received: <%= @received_invitations.count %></h5></p>
</div> 
<% end %>

app/views/invitations/_sent_invitations_table.html.erb
<% if @sent_invitations.any? %>
<div class="div-table">
<table class="table">
  <thead>  
    <tr>
      <th>Unconnected</th>
      <th>Email</th>
    	<th>Added at</th>
    </tr>
  </thead>
  <tbody>
    <% @sent_invitations.each do |invitation| %>
      <tr>
        <td>
          <div class="btn-group">
            <button type="button" class="btn btn-mini btn-warning btn-remind" data-loading-text="Reminded">Remind</button>
            <button class="btn btn-mini dropdown-toggle" data-toggle="dropdown">
              <span class="caret"></span>
            </button>
            <ul class="dropdown-menu">
              <li><%= link_to "Cancel", '#' %></li>
            </ul>
          </div>          
        </td>
        <td><%= invitation.email %></td>
        <td><%= invitation.created_at.to_formatted_s(:db) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<div>
  <p><h5>&nbsp;&nbsp;&nbsp;Total Unconnected: <%= @sent_invitations.count %></h5></p>
</div> 
<% end %>

app/views/invitations/index.html.erb
<% provide(:title, 'Contacts') %>
<% provide(:sub_title, 'Pending') %>
<div class="row">
  <div class="span7">
    <%= render 'invitations/received_invitations_table' %>
  </div>
  <div class="span5">
    <%= render 'invitations/sent_invitations_table' %>
  </div>
  <% if !@received_invitations.any? && !@sent_invitations.any? %>
  	<div class="span12">
  	  <p><h4>You don't have contact in pending status</h4></p>
  	</div>
  <% end %>
</div>

app/views/invitations/new_signin.html.erb
<% provide(:title, 'Sign in to Send information') %>
<div class= "span4 offset4">
  <%= render 'invitations/accept_invitation_signin_form' %>
  <br>
</div>

app/views/invitations/new_signup.html.erb
<% provide(:title, 'Send information') %>
<div class= "span4 offset4">
  <%= render 'invitations/accept_invitation_signup_form' %>
  <br>
  <p>Alreday have an account?<br><%= link_to "Sign in to send your information back", invitations_new_signin_path + "?token=#{params[:token]}" %></p>
</div>

app/views/invitations/show.html.erb
<% provide(:title, 'Contacts') %>
<% provide(:sub_title, 'Pending') %>
<div class="row">
  <div class="span7">
    <%= render 'invitations/received_invitations_table' %>
  </div>
  <div class="span5">
    <%= render 'invitations/sent_invitations_table' %>
  </div>
  <% if !@received_invitations.any? && !@sent_invitations.any? %>
  	<div class="span12">
  	  <p><h4>You don't have contact in pending status</h4></p>
  	</div>
  <% end %>
</div>