config/routes.rb
Kit::Application.routes.draw do

  root to: 'webpages#landing'

  resources :users, only: [:new, :create, :index, :update, :show, :destroy]
  match '/signup',  to: 'users#new'

  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  resources :invitations, only: [:index, :create]
  match '/invitations_new_signup', to: 'invitations#new_signup'
  match '/invitations_accept_signup', to: 'invitations#accept_signup', via: :post
  match '/invitations_new_signin', to: 'invitations#new_signin'
  match '/invitations_accept_signin', to: 'invitations#accept_signin', via: :post

  resources :contacts, only: [:index]
  
  resources :passwords, only: [:new, :create, :edit, :update]
  match '/reset_new',  to: 'passwords#reset_new'
  match '/reset_update',  to: 'passwords#reset_update', via: :put

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
  	  <%= link_to "JingsApp (Beta)", root_path, class: "brand", id: "logo", tabindex: "-1" %>
	    <nav>
    	  <ul class="nav nav-pills pull-right">
    	    <% if signed_in? %>                        
    	      <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown", tabindex= "-1">
                <%= current_user.name %>
                <% if admin? %>
                  <small>(Admin)</small>
                <% end %>
                <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">                
                <li><%= link_to "Account", edit_password_path(current_user) %></li>
                <li class="divider"></li>
                <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
              </ul>
            </li>
	  	    <% else %>
	  	      <li>
              <%= link_to "About", 'http://www.jingzhang.info/', tabindex: "-1", target: "_blank" %>
            </li>
	  	    <% end %>
	      </ul>
	    </nav>
	  </div>
	</div>
</header>

app/views/layouts/_sub_nav.html.erb
<nav>
<ul class="nav nav-tabs">
  <li>
    <a href="#new_contact_modal" role="button" class="btn" data-toggle="modal" rel="tooltip" title="Add new contact">
    <i class="icon-plus"></i>
    </a>
  </li>
  <% if admin? %>
    <li <% if yield(:sub_title) == "All Users" %>class="active"<% end %>>
      <%= link_to 'All Users', users_path, rel: "tooltip", title: "List all users" %>
    </li>
  <% end %>
  <li <% if yield(:sub_title) == "Contacts" %>class="active"<% end %>>
    <%= link_to '<i class="icon-list-alt"></i>'.html_safe, contacts_path, rel: "tooltip", title: "Your contacts" %>
  </li>
  <li <% if yield(:sub_title) == "Pending" %>class="active"<% end %>>
    <%= link_to '<i class="icon-envelope"></i>'.html_safe, invitations_path, rel: "tooltip", title: "Pending contacts" %>
  </li>
  <li class="<% if yield(:title) == current_user.name && yield(:sub_title) == "Profile" %>active<% end %> pull-right">
    <a href="/users/<%= current_user.id %>" rel="tooltip" title="Your profile"><i class="icon-user"></i></a>
  </li>
  <% if yield(:title) != current_user.name && yield(:sub_title) == "Profile" %>
    <li class="active">
      <%= link_to @user.name, '#', rel: "tooltip", title: "Information of #{yield(:title)}" %>
    </li>
  <% end %>
  <% if yield(:title) == "Account" %>
    <li class="active pull-right">
      <%= link_to "Account Settings", '#', rel: "tooltip", title: "Account settings" %>
    </li>
  <% end %>
</ul>

<div id="new_contact_modal" class="modal hide" tabindex="-1" role="dialog" aria-labelledby="new_contact_label" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="new_contact_label">New Contact</h3>
  </div>
  <div class="modal-body">
    <div class="accordion-group">
      <div class="accordion-heading">
        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
          Email
        </a>
      </div>
      <div id="collapseOne" class="accordion-body collapse in">
        <div class="accordion-inner">
          <%= form_for @invitation do |f| %>
            <%= f.hidden_field :user_id, value: current_user.id %>
            <%= f.text_field :email, class: "input-xlarge", placeholder: "Input email to Add" %>
        </div>
      </div>
    </div>
    <div class="accordion-group">
      <div class="accordion-heading">
        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
          Optional Information
        </a>
      </div>
      <div id="collapseTwo" class="accordion-body collapse">
        <div class="accordion-inner">
          <%= f.text_field :name, class: "input-xlarge", placeholder: "Name" %><br>
          <%= f.text_field :phone, class: "input-xlarge", placeholder: "Phone Number" %><br>
          <%= f.text_area :message, class: "input-xlarge", rows: 5 ,placeholder: "Leava a message" %> 
        </div>
      </div>
    </div>            
  </div>
  <div class="modal-footer">
    <%= f.submit "Save", class: "btn btn-primary pull-left" %>
    <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>    
    <% end %>
  </div>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JingsApp | <%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body>
  <%= render 'layouts/header' %>
  <br><br><br><br><br>
  <div class="container">
    <% if signed_in? %>
      <%= render 'layouts/sub_nav' %>
    <% end %>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
	  <%= yield %>
  </div>
</body>
</html>